<a href="https://colab.research.google.com/github/KARISHMA674/data-analytics./blob/main/asian_paints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("/content/Quote-Equity-ASIANPAINT-EQ-27-08-2025-27-08-2026.csv")
print(df)

            DATE SERIES      OPEN      HIGH       LOW PREV. CLOSE       LTP  \
0    27-Aug-2026     EQ  2,637.90  2,655.90  2,627.90    2,626.50  2,631.00
1    26-Aug-2026     EQ  2,660.90  2,678.70  2,626.50    2,639.80  2,626.50
2    25-Aug-2026     EQ  2,631.00  2,640.00  2,605.20    2,640.80  2,639.80
3    24-Aug-2026     EQ  2,640.40  2,642.70  2,622.00    2,640.00  2,640.80
4    21-Aug-2026     EQ  2,620.20  2,644.00  2,615.50    2,625.20  2,640.00
..           ...    ...       ...       ...       ...         ...       ...
243  03-Sep-2025     EQ  2,530.00  2,565.10  2,527.30    2,540.00  2,560.00
244  02-Sep-2025     EQ  2,569.00  2,571.90  2,531.00    2,570.20  2,538.00
245  01-Sep-2025     EQ  2,518.00  2,577.80  2,515.10    2,518.60  2,570.00
246  29-Aug-2025     EQ  2,491.00  2,531.60  2,490.00    2,489.00  2,520.00
247  28-Aug-2025     EQ  2,465.00  2,528.00  2,465.00    2,481.40  2,490.00

        CLOSE      VWAP     52W H     52W L     VOLUME              VALUE  \
0    2,631.00  2,641.67  2,985.70  2,115.00   5,25,106  1,38,71,55,598.30
1    2,626.50  2,649.10  2,985.70  2,115.00   3,39,110    89,83,37,657.70
2    2,639.80  2,620.62  2,985.70  2,115.00   4,79,480  1,25,65,34,871.40
3    2,640.80  2,629.74  2,985.70  2,115.00   3,55,289    93,43,18,394.60
4    2,640.00  2,627.67  2,985.70  2,115.00   3,30,334    86,80,07,102.50
..        ...       ...       ...       ...        ...                ...
243  2,553.90  2,550.67  3,394.90  2,124.75   9,25,847  2,36,15,33,560.30
244  2,540.00  2,549.56  3,394.90  2,124.75  10,24,054  2,61,08,85,776.30
245  2,570.20  2,559.95  3,394.90  2,124.75  13,14,833  3,36,59,06,195.70
246  2,518.60  2,513.22  3,394.90  2,124.75  17,98,653  4,52,04,02,451.20
247  2,489.00  2,505.93  3,394.90  2,124.75  14,85,769  3,72,32,34,769.70

    NO. OF  TRADES
0           45,120
1           23,691
2           32,656
3           28,868
4           21,795
..             ...
243         56,343
244         85,903
245         62,406
246       1,05,469
247       1,05,181

[248 rows x 14 columns]

In [13]:
df.head()

,DATE,SERIES,OPEN,HIGH,LOW,PREV. CLOSE,LTP,CLOSE,VWAP,52W H,52W L,VOLUME,VALUE,NO. OF TRADES
0,27-Aug-2026,EQ,"2,637.90","2,655.90","2,627.90","2,626.50","2,631.00","2,631.00","2,641.67","2,985.70","2,115.00","5,25,106","1,38,71,55,598.30","45,120"
1,26-Aug-2026,EQ,"2,660.90","2,678.70","2,626.50","2,639.80","2,626.50","2,626.50","2,649.10","2,985.70","2,115.00","3,39,110","89,83,37,657.70","23,691"
2,25-Aug-2026,EQ,"2,631.00","2,640.00","2,605.20","2,640.80","2,639.80","2,639.80","2,620.62","2,985.70","2,115.00","4,79,480","1,25,65,34,871.40","32,656"
3,24-Aug-2026,EQ,"2,640.40","2,642.70","2,622.00","2,640.00","2,640.80","2,640.80","2,629.74","2,985.70","2,115.00","3,55,289","93,43,18,394.60","28,868"
4,21-Aug-2026,EQ,"2,620.20","2,644.00","2,615.50","2,625.20","2,640.00","2,640.00","2,627.67","2,985.70","2,115.00","3,30,334","86,80,07,102.50","21,795"

In [11]:
df.tail()

,DATE,SERIES,OPEN,HIGH,LOW,PREV. CLOSE,LTP,CLOSE,VWAP,52W H,52W L,VOLUME,VALUE,NO. OF TRADES
243,03-Sep-2025,EQ,"2,530.00","2,565.10","2,527.30","2,540.00","2,560.00","2,553.90","2,550.67","3,394.90","2,124.75","9,25,847","2,36,15,33,560.30","56,343"
244,02-Sep-2025,EQ,"2,569.00","2,571.90","2,531.00","2,570.20","2,538.00","2,540.00","2,549.56","3,394.90","2,124.75","10,24,054","2,61,08,85,776.30","85,903"
245,01-Sep-2025,EQ,"2,518.00","2,577.80","2,515.10","2,518.60","2,570.00","2,570.20","2,559.95","3,394.90","2,124.75","13,14,833","3,36,59,06,195.70","62,406"
246,29-Aug-2025,EQ,"2,491.00","2,531.60","2,490.00","2,489.00","2,520.00","2,518.60","2,513.22","3,394.90","2,124.75","17,98,653","4,52,04,02,451.20","1,05,469"
247,28-Aug-2025,EQ,"2,465.00","2,528.00","2,465.00","2,481.40","2,490.00","2,489.00","2,505.93","3,394.90","2,124.75","14,85,769","3,72,32,34,769.70","1,05,181"

In [12]:
df.describe()

,DATE,SERIES,OPEN,HIGH,LOW,PREV. CLOSE,LTP,CLOSE,VWAP,52W H,52W L,VOLUME,VALUE,NO. OF TRADES
count,248,248,248,248,248,248,248,248,248,248,248,248,248,248
unique,248,1,232,238,238,245,232,245,248,15,3,248,248,248
top,27-Aug-2026,EQ,"2,880.00","2,655.90","2,720.00","2,639.80","2,640.00","2,639.80","2,641.67","2,985.70","2,124.75","5,25,106","1,38,71,55,598.30","45,120"
freq,1,248,3,2,2,2,4,2,1,181,131,1,1,1